#!/usr/bin/env bash

function list{
	cmakevm.py --list
}

function install{
	VERSION_TO_INSTALL = $1
	NEW_CMAKE_PATH=`cmakevm.py install ${VERSION_TO_INSTALL}`
}

while [[ $# > 1 ]]
do
key="$1"

case $key in
    -i|--install)
    VERSION_TO_INSTALL="$2"
    shift # past argument
    ;;
    -l|--list)
    SEARCHPATH="$2"
    shift # past argument
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done

echo FILE EXTENSION  = "${EXTENSION}"
echo SEARCH PATH     = "${SEARCHPATH}"
echo LIBRARY PATH    = "${LIBPATH}"
echo "Number files in SEARCH PATH with EXTENSION:" $(ls -1 "${SEARCHPATH}"/*."${EXTENSION}" | wc -l)
if [[ -n $1 ]]; then
    echo "Last line of file specified as non-opt/last argument:"
    tail -1 $1
fi
